all: square cube random-positive-number cube-root

square:
	cd Square_function/Tests && \
	$(CSI) unit_test.scm

cube:
	cd Cube_function/Tests && \
	$(CSI) unit_test.scm

random-positive-number:
	cd Random_positive_number_generator/Tests && \
	$(CSI) unit_test.scm

cube-root:
	cd Cube_root/Tests && \
	$(CSI) unit_test.scm && $(CSI) pbt.scm
